---
  :imap:
    :host: ''
    :user: ''
    :password: ''
    :port: 993
    :folder: ''
    :ssl: true
    :interval: 10
  :irc:
    :server: irc.efnet.net
    :port: 6667
    :nick: fbot12
    :user: silicon
    :password: ''
    :channels: [ '#baykids' ]
